### ISSUE TITLE
Produce monthly VP level update

### ISSUE THREAD

**Issue by samiatoui** [PHACDataHub/iidi#15]
VP Steering Committee occurs every month. Prior to VPSC, IPPM to provide a briefing note to CIO. 

Feedback to current version of dashboard:
•	It needed to be more granular
•	What is on track and what is not
•	What are the roadblocks?

Here is the current [template] for the word document(https://022gc.sharepoint.com/:w:/r/sites/ProjectImmunizationRecordGatewayDSFB-SDPI/_layouts/15/Doc.aspx?sourcedoc=%7BED3F2284-E4F2-4671-A4B6-8FB2C2ED54DB%7D&file=IIDI%20Monthly%20Project%20Update.docx&action=default&mobileredirect=true): 

Here is the template for the [slide version](https://022gc.sharepoint.com/:p:/r/sites/ProjectImmunizationRecordGatewayDSFB-SDPI/_layouts/15/Doc.aspx?sourcedoc=%7BA0602FD6-7162-4855-8908-4438BDC431A7%7D&file=Interoperable%20Immunization%20Data%20Initiative%20Project%20Dashboard%20Sep%2024%202024.pptx&action=edit&mobileredirect=true) of the dashboard. 

```[tasklist]
### Tasks
- [x] Revise dashboard template based on feedback
- [x] Update dashboard content
- [x] Create briefing note/monthly report
- [x] Confirm template with Seb and Henry
- [ ] Send BN to DHTB for feedback/review
- [ ] Finalize update
- [ ] Distribute through appropriate channels
```

**Comment by samiatoui** [comment]
@AndrewLoPHAC has created the first monthly dashboard to use as an example. pending review.

**Comment by hkoo138** [comment]
Need to decide the timing of release and format

Next VP meetings are:
Oct 25
Nov 27
Dec TBD
Jan 22
Feb 26
Mar 26
Apr 25
May 28
Jun 25

**Comment by ChristineP2024** [comment]
Need to confirm who will produce these moving forward.

**Comment by ChristineP2024** [comment]
VP meeting has been postponed to Nov. 4th. Henry will update the monthly dashboard.

**Comment by samiatoui** [comment]
VP meeting moved to the 18th
