### ISSUE TITLE
Develop presentation for HC Technical Table

### ISSUE THREAD

**Issue by ChristineP2024** [PHACDataHub/iidi#24]
```[tasklist]
### Tasks
- [ ] Confirm approach
- [ ] Develop slides
- [ ] Prep for dry run
- [ ] Conduct dry run
- [ ] Send in presentation
- [ ] Confirm logistics
- [ ] Deliver
```

**Comment by hkoo138** [comment]
- Due date to PHDSC on Oct 21
- Henry will look after translation
