### ISSUE TITLE
Technical Deck to present to PHDSC for Oct 31 at 3 - 330pm (Sebs/Simardeep)

### ISSUE THREAD

**Issue by hkoo138** [PHACDataHub/iidi#31]
20 minute agenda item, for information + technical briefing
Seb and Simardeep to present a technical walkthrough of the federated data PoC
CIHI to do a similar technical briefing on Pathways; to provide more information on that project to members given Saskatchewan and Manitoba signalled an interest at the last PHDSC meeting.

Due 2 weeks before the actual presentation on Oct 31 at 3 - 330pm; to be done the week of Oct 14.

To be presented by Sebs and Simardeep
Link to [deck](https://022gc.sharepoint.com/:p:/r/sites/ProjectImmunizationRecordGatewayDSFB-SDPI/_layouts/15/Doc.aspx?sourcedoc=%7BE6BAD86E-FD6A-4612-855F-8197B8EE08F1%7D&file=Federated%20Data%20Pilot%20-%20Update%20to%20PHDSC%20October%2031%202024.pptx&action=edit&mobileredirect=true)
```[tasklist]
### Tasks
- [x] Confirm approach
- [x] Develop slides
- [x] Send to Seb for review
- [x] Send to Henry; conduct a walkthough
- [ ] Prep
- [ ] Conduct dry run (TBC if we need this)
- [ ] Deliver
```

```[tasklist]
### Tasks
```

**Comment by ChristineP2024** [comment]
Deck is drafted; Christine to give it one last look before flipping it to Simardeep.

**Comment by DurandSC** [comment]
Let me know... I am leaving at 15:00 tomorrow

**Comment by ChristineP2024** [comment]
Deck now with Simardeep - one slide I'm struggling with. Will send what we have to @DurandSC by EOD.

**Comment by simardeep1792** [comment]
@ChristineP2024 I have added the slide for the Technical Architecture

**Comment by ChristineP2024** [comment]
Walkthrough of the presentation scheduled Oct. 21.

**Comment by ChristineP2024** [comment]
This presentation is postponed. There was a misunderstanding re: who would schedule this technical walkthrough. Stay tuned for new date from Henry.
