### ISSUE TITLE
Prep Sub WG Meeting 2

### ISSUE THREAD

**Issue by ChristineP2024** [PHACDataHub/iidi#34]
The Sub WG meetings every 2 weeks; 2nd meeting is on Oct. 17th. Prep includes: 
- Main topic: The PoC
- Meeting material includes 
- Agenda
- Deck
- Additional docs (TBC)
```[tasklist]
### Tasks
- [x] Confirm the approach
- [x] Prep the agenda
- [x] Prep the deck
- [x] Prep additional docs
- [x] Send to Henry for review
- [x] Sami to upload in Git Hub
- [x] Christine to prep the email to meeting participants and send to Frida
- [x] Confirm readiness
- [x] Produce the meeting notes
- [x] Send package
```

**Comment by ChristineP2024** [comment]
Draft meeting documentation saved [here](https://022gc.sharepoint.com/sites/ProjectImmunizationRecordGatewayDSFB-SDPI/Shared%20Documents/Forms/AllItems.aspx?ga=1&LOF=1&id=%2Fsites%2FProjectImmunizationRecordGatewayDSFB%2DSDPI%2FShared%20Documents%2FProduct%20Team%2FSub%2DWorking%20Group%2FMeetings%2FOct%2017%202024&viewid=f770724e%2Da683%2D4996%2Dabd7%2D3a1e47c20913
):

**Comment by ChristineP2024** [comment]
Upload in the repo:
- Updated deck
- Meeting notes
- videos

Send an email with link to the repo and instructions on how to access by Oct. 22.
