### ISSUE TITLE
Measures of a Successful Pilot - One Pager

### ISSUE THREAD

**Issue by ChristineP2024** [PHACDataHub/iidi#46]
One-pager describing at a high level what indicators we could use to measure the success of this pilot. This document to be shared with FPTI WG on Oct. 28th. 

Link to [draft document.](https://022gc.sharepoint.com/:w:/r/sites/ProjectImmunizationRecordGatewayDSFB-SDPI/Shared%20Documents/Product%20Team/1-Planning/Measures%20of%20Success%20Federated%20Data%20Pilot.docx?d=w20d0d22a48ac420ba4fc61f571f3370c&csf=1&web=1&e=xLfTvZ)
```[tasklist]
### Tasks
- [x] Christine to develop one-page draft
- [x] Team to meet to discuss
- [ ] Henry to share with IDVPB
- [ ] Henry to incorporate in the deck
```
