### ISSUE TITLE
Sub WG Package for Kick Off

### ISSUE THREAD

**Issue by samiatoui** [PHACDataHub/iidi#6]
Includes:
- agenda
- deck
- List of documentation
- Documentation repository accessible by ON, BC and CIHI
```[tasklist]
### Tasks
- [ ] Andrew to create a list of documentation as a seperate document to be sent via email
- [x] Simardeep to review list of documentation
- [ ] Share deck with Henry for review
- [ ] Conduct dry run ahead of meeting
- [ ] Sami to create a document repository in Git Hub
- [ ] Christine to confirm with Henry documents can be public
```

**Comment by simardeep1792** [comment]
@Samiatoui, I wanted to check in regarding this issue. I'm not entirely sure why it's still open or how it’s relevant at this point. Could you kindly provide some context or let me know if it’s okay to close it?

Thank you for your help!

**Comment by samiatoui** [comment]
@simardeep1792 this item should be closed, I see that it is not even tracked in our kanban.
